### ISSUE TITLE
Failed adding alarm

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-assistant/skill_Reminder#14]
Adding a alarm, for 1 minute, results in this after she asked for a message:

```
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 1028, in dispatchMessage
    consumed = skillInstance.onMessageDispatch(session)
  File "/home/pi/ProjectAlice/core/base/model/AliceSkill.py", line 555, in onMessageDispatch
    ret = function(session=session)
  File "/home/pi/ProjectAlice/skills/Reminder/Reminder.py", line 252, in processTheSpecifiedTime
    self.processAndStoreReminder(session, secs)
  File "/home/pi/ProjectAlice/skills/Reminder/Reminder.py", line 269, in processAndStoreReminder
    timeStampForDb = self.createEpochTimeStamp(secs)
  File "/home/pi/ProjectAlice/skills/Reminder/Reminder.py", line 353, in createEpochTimeStamp
    timeStampForDatabase = datetime.now() + timedelta(seconds=seconds)
TypeError: unsupported type for timedelta seconds component: str
```

**Comment by LazzaAU** [comment]
Un able to re create since re doing the recent code changes, will re open if I come across it
